name: zenith
description: An all-in-one cryptocurrency tool for managing portfolios and tracking real-time prices.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  file_picker: ^5.5.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  csv: ^5.0.2
  logger: ^2.0.2+1
  google_fonts: ^6.1.0
  flutter_blurhash: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
